image: node:10.5.0

cache:
  paths:
    - node_modules/

stages:
  # - setup
  # - build
  - deploy

# .setup-script: &setup-script |
#   # The setup script
#   yarn install

# setup:
#   stage: setup
#   only:
#     - master
#   script:
#     - *setup-script

# .build-script: &build-script |


# build:
#   stage: build
#   only:
#     - master
#   script: 
#     - *build-script
    
.deploy-script: &deploy-script |
  yarn install
  yarn build
  yarn export
  npx semantic-release
  ls
  cd out
  git add .
  git commit -m "update: ${CI_COMMIT_MESSAGE}"
  git push origin master

deploy:
  stage: deploy
  only:
    - master
  script:
    - *deploy-script
