
version: 2
jobs:
  build:
    working_directory: ~/portfolio
    docker:
      - image: circleci/node:10.5.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: yarn install
      - run:
          name: Update submodule
          command: |
            git submodule init
            git submodule update
      - run:
          name: Building and exporting
          command: |
            yarn build
            yarn export
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./out
      - run:
          name: Deploy to gh pages 1
          working_directory: ~/portfolio/out
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "hannes.rabo@gmail.com"
            git config user.name "hannesrabo"
      - run:
          name: Deploy to gh pages 2
          working_directory: ~/portfolio/out
          command: |
            ls
      - run:
          name: Deploy to gh pages 3
          working_directory: ~/portfolio/out
          command: |
            git add .
      - run:
          name: Deploy to gh pages 4
          working_directory: ~/portfolio/out
          command: |
            git commit --allow-empty -m "Update"
      - run:
          name: Deploy to gh pages 5
          working_directory: ~/portfolio/out
          command: |
            git remote rm origin
            git remote add origin https://hannesrabo:${GITHUB_TOKEN}@github.com/hannesrabo/hannesrabo.github.io.git
            git push origin master
      - run:
          name: Creating a release
          command: npx semantic-release
      # - run:
      #     name: test
      #     command: npm test
      # - run:
      #     name: code-coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
      # - store_test_results:
      #     path: test-results.xml

